# 22.3.15. Troubleshooting Connector/J Applications

###22.3.15. Troubleshooting Connector/J Applications

这一节介绍在使用MySQL Connector/J的过程中遇到的最常见的问题及其解决办法。

问题：

* `23.3.15.1`:当我使用MySQL Connector/J连接到数据库时，碰到了下面的异常：

```java

SQLException: Server configuration denies access to data source
SQLState: 08001
VendorError: 0

```

怎么会这样？我使用MySQL的客户端命令行就可以连接MySQL服务器。

* `23.3.15.2`:我的应用程序抛出了一个SQLException"No Suitable Driver"。为什么会抛出这样的异常？

* `23.3.15.3`:我尝试在applet或者应用中使用MySql Connector/J，然后得到了类似下面的异常：

```java

SQLException: Cannot connect to MySQL server on host:3306.
Is there a MySQL server running on the machine/port you
are trying to connect to?
(java.security.AccessControlException)
SQLState: 08S01
VendorError: 0 

```

* `23.3.15.4`: 我有一个servlet应用，这个应用已经成功运行了一天了，但是晚上停止了：

* `23.3.15.5`: 我尝试使用JDBC2.0更新结果集，但是我得到了一个异常说结果集不可更新。

* `23.3.15.6`: 我使用Connector/J不能连接到MySQL服务器，但是我确信连接参数都是正确的。

* `23.3.15.7`: 我在我的应用中尝试连接到MySQL服务器，但是得到了下面的异常栈：

```java

java.net.SocketException
MESSAGE: Software caused connection abort: recv failed
STACKTRACE:
java.net.SocketException: Software caused connection abort: recv failed
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(Unknown Source)
at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:1392)
at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:1414)
at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:625)
at com.mysql.jdbc.Connection.createNewIO(Connection.java:1926)
at com.mysql.jdbc.Connection.<init>(Connection.java:452)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:411)

```

* `23.3.15.8`: 我的应用程序是使用JBoss部署的，并且我使用事务来处理MySQL数据库的声明。在大负载下，我得到了一个错误和错误栈，但是这仅仅在一个特定的时间和特定的负载下发生。
* `23.3.15.9`: 使用`gcj`，在处理某个字符串时产生了一个`java.io.CharConversionException`异常。
* `23.3.15.10`: 更新表时，表的主键要么是`FLOAT`类型，要么是组合键，但是当使用`FLOAT`类型时更新表却产生了一个异常。
* `23.3.15.11`: 虽然要使用JDBC插入二进制块的大小小于`max_allowed_packet`，但还是得到了一个`EN_NET_PACKET_TOO_LARGE`异常。
* `23.3.15.12`: 如果你接收到了一个类似下面的错误信息该怎么做呢:"Communications link failure – Last packet sent to the server was X ms ago"?
* `23.3.15.13`: 为什么Connector/J没有重连到MySQL，并且在会话失败之后重用了声明，而不是抛出一个异常，虽然我使用了`autoReconnect`连接字符串？
* `23.3.15.14`: 我如何在Connector/J中使用3字节的UTF8编码？
* `23.3.15.15`: 我如何在Connector/J中使用4字节的UTF8编码，`utf8mb4`。
* `23.3.15.16`: 使用`useServerPrepStmts=false`并且某种字符编码可以导致插入BLOB类型数据时崩溃。如何避免这个问题。

#####Questions and Answers

######23.3.15.1: When I try to connect to the database with MySQL Connector/J, I get the following exception:

```java

SQLException: Server configuration denies access to data source
SQLState: 08001
VendorError: 0

```
######What is going on? I can connect just fine with the MySQL command-line client.

MySQL Connector/J必须使用TCP/IP套接字来连接MySQL，因为Java不支持Unix Domain Sockets。因此，当MySQL Connector/J连接到MySQL时，MySQL服务中的安全管理将使用其授权表来确定能否允许当前连接。

用户必须使用`GRANT`语句添加必要的安全凭证到MySQL服务器。参见[13.7.1.4节, “GRANTSyntax”][13-7-1-4]获取详细信息。

>#####注意#####
>在`mysql`命令行测试连接性将不会起作用，除非添加了"host"标识，并且有时使用除了`localhost`的主机名。 如果使用`localhost`这样特别的主机名。，`mysql`命令行客户端将使用Unix domain sockets。如果测试到`localhost`的连接性，那么使用`127.0.0.1`这个主机名替换。
>#####警告#####
>MySQL中的不当权限和许可更改将导致安装的服务器具备最佳的安全特性。

######23.3.15.2: My application throws an SQLException 'No Suitable Driver'. Why is this happening?

发生这个错误有三个可能的原因：

* Connector/J不在`CLASSPATH`中，参见[Section 22.3.3节, “Connector/J Installation”][22-3-3]。
* 连接字符串的URL是错误的，或者引用了一个错误的JDBC驱动。
* 当使用DriverManager时，`jdbc.drivers`系统属性没有指定Connector/J驱动的存放路径。

######23.3.15.3: I'm trying to use MySQL Connector/J in an applet or application and I get an exception similar to:

```java
SQLException: Cannot connect to MySQL server on host:3306.
Is there a MySQL server running on the machine/port you
are trying to connect to?
(java.security.AccessControlException)
SQLState: 08S01
VendorError: 0 
```

要么你正在运行一个Applet，你的MySQL服务器安装时选择了"skip-networking"选项，或者你的MySQl服务器被防火墙阻止访问。

Applet仅仅能够连接到运行为applet提供class文件的Web服务器的机器。这意味着MySQL必须运行在同样的机器上面（或者有一些端口转发措施）才能使访问applet正常。这也意味着必须在本地文件系统上测试applet，并且总是将applet部署到Web服务器上。

MySQL Connector/J仅仅使用TCP/IP协议与MySQL交互，由于Java不支持Unix domain socket。如果MySQL以"skip-networking"选项启动，或者被防火墙阻止，那么TCP/IP与MySQL的交互会受影响。

如果MySQL默认以"skip-networking"选项启动（例如Debian Linux的MySQL服务器会这样启动），那么必须在文件`/etc/mysql/my.cnf`或`/etc/my.cnf`文件中将其注释掉。当然`my.conf`文件也可能存在于MySQL服务器端的`data`目录，或者任何其他地方（这依赖于MySQL在操作系统中编译的具体情况而定）。对于MySQL的二进制版本，可以在文件`/etc/my.conf`和`datadir/my.conf`找到。如果MySQL服务被防火墙阻止了，那么需要配置防火墙使其允许Java代码所在的主机到MySQL服务器中运行MySQL服务器端口（默认为3306）的TCP/IP连接。

######23.3.15.4: I have a servlet/application that works fine for a day, and then stops working overnight

如果MySQL连接8小时没有活动，则会被关闭。所以你需要使用连接池来处理已经使用过的连接或者使用`autoReconnect`参数（参见[22.3.5.1节, “Driver/Datasource Class Names, URL Syntax and Configuration Properties for Connector/J”][22-3-5-1]）。

同样，在应用程序中可以捕捉`SQLException`异常来处理，而不是知道在应用程序退出之后处理。这是一个很好的编程习惯。在处理查询过程中当遇到网络连接错误的时候，MySQL Connector/J将设置`SQLState`（参见API文档中的`java.sql.SQLException.getSQLState()`方法）为`08S01`。尝试从这点上重连MySQL。

下面的例子展示了处理这些异常的代码：
######Example 22.12. Connector/J: Example of transaction with retry logic

```java

public void doBusinessOp() throws SQLException {
Connection conn = null;
Statement stmt = null;
ResultSet rs = null;
//
// How many times do you want to retry the transaction
// (or at least _getting_ a connection)?
//
int retryCount = 5;
boolean transactionCompleted = false;
do {
try {
conn = getConnection(); // assume getting this from a
// javax.sql.DataSource, or the
// java.sql.DriverManager
conn.setAutoCommit(false);
//
// Okay, at this point, the 'retry-ability' of the
// transaction really depends on your application logic,
// whether or not you're using autocommit (in this case
// not), and whether you're using transactional storage
// engines
//
// For this example, we'll assume that it's _not_ safe
// to retry the entire transaction, so we set retry
// count to 0 at this point
//
// If you were using exclusively transaction-safe tables,
// or your application could recover from a connection going
// bad in the middle of an operation, then you would not
// touch 'retryCount' here, and just let the loop repeat
// until retryCount == 0.
//
retryCount = 0;
stmt = conn.createStatement();
String query = "SELECT foo FROM bar ORDER BY baz";
rs = stmt.executeQuery(query);
while (rs.next()) {
}
rs.close();
rs = null;
stmt.close();
stmt = null;
conn.commit();
conn.close();
conn = null;
transactionCompleted = true;
} catch (SQLException sqlEx) {
//
// The two SQL states that are 'retry-able' are 08S01
// for a communications error, and 40001 for deadlock.
//
// Only retry if the error was due to a stale connection,
// communications problem or deadlock
//
String sqlState = sqlEx.getSQLState();
if ("08S01".equals(sqlState) || "40001".equals(sqlState)) {
retryCount -= 1;
} else {
retryCount = 0;
}
} finally {
if (rs != null) {
try {
rs.close();
} catch (SQLException sqlEx) {
// You'd probably want to log this...
}
}
if (stmt != null) {
try {
stmt.close();
} catch (SQLException sqlEx) {
// You'd probably want to log this as well...
}
}
if (conn != null) {
try {
//
// If we got here, and conn is not null, the
// transaction should be rolled back, as not
// all work has been done
try {
conn.rollback();
} finally {
conn.close();
}
} catch (SQLException sqlEx) {
//
// If we got an exception here, something
// pretty serious is going on, so we better
// pass it up the stack, rather than just
// logging it...
throw sqlEx;
}
}
}
} while (!transactionCompleted && (retryCount > 0));
}

```

>#####注意######
>不推荐使用`autoReconnect`选项因为没有安全的方法重连到MySQL服务器，现有的方法会有连接垮掉或者数据库信息丢失的风险。更好的方式是使用连接池的方式，连接池将使得应用程序使用连接池中可用的连接来连接到MySQL服务器。`autoReconnect`方式已经被废除了，并且将在以后的版本中移除。

######23.3.15.5: I'm trying to use JDBC 2.0 updatable result sets, and I get an exception saying my result set is not updatable.

由于MySQL没有行标识符，MySQL Connector/J仅仅能更新从表中查询出的至少有一个主键的结果集，查询中必须选择主键列，并且查询仅仅在一张表上进行（也就是没有连接操作）。这在JDBC规范中指出了。

注意这个问题仅仅在使用可更新的结果集时出现，出现的原因是Connector/J不能保证在没有行的唯一引用的条件下在结果集中识别的正确的行。如果你正在表中使用`UPDATE`或者`DELETE`声明，那么没有必要获取到表中的唯一字段，在这种情况下可以在`WHERE`子句中指定查询条件。

######23.3.15.6: I cannot connect to the MySQL server using Connector/J, and I'm sure the connection parameters are correct.

确保服务器上的`skip-networking`选项没有启用。Connector/J必须使用TCP/IP协议与服务器交互；指定套接字是不受支持的。同时确保你没有通过防火墙或者其他安全网络系统过滤连接。更多信息参考[C.5.2.2节, “Can't connect to [local] MySQL server”][c-5-2-3]

######23.3.15.7: I am trying to connect to my MySQL server within my application, but I get the following error and stack trace:

```java

java.net.SocketException
MESSAGE: Software caused connection abort: recv failed
STACKTRACE:
java.net.SocketException: Software caused connection abort: recv failed
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(Unknown Source)
at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:1392)
at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:1414)
at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:625)
at com.mysql.jdbc.Connection.createNewIO(Connection.java:1926)
at com.mysql.jdbc.Connection.<init>(Connection.java:452)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:411)

```

上面的错误表明你正在使用老版本的Connector/J的JDBC驱动（2.0.14或者3.0.x）并且常会连接到4.1x版本或者更高版本的MySQL服务器。老版本的驱动与4.1版本或更高版本的MySQL不兼容，因为他们不支持新的认证机制。

很可能在应用程序目录或者`CLASSPATH`中包含老版本Connector/J包。

######23.3.15.8: My application is deployed through JBoss and I am using transactions to handle the statements on the MySQL database. Under heavy loads, I am getting an error and stack trace,but these only occur after a fixed period of heavy activity

这是JBoss的问题，而不是Connector/J的问题，来连接到MySQL来处理事务。在高负载下，完成事务所需的时间会增加，这个错误的原因是事务处理的时间超过了预定于超时时间。

你可以通过为`TransactionManagerService`来设置`TransactionTimeout`属性来增加超时时间，在`/conf/jboss-service.xml`文件（4.0.3版本之前）或者`deploy/jta-service.xml`文件中(4.0.3版本或更高版本的JBoss)。参见JBoss 的wiki获取更多`TransactionTimeout`的信息。

######23.3.15.9: When using `gcj`, a `java.io.CharConversionExceptionexception` is raised whenworking with certain character sequences。

这是`gcj`的问题，当`gcj`遇到未知的字符或者不能转换时，就会出现这个问题。在连接字符串中添加`useJvmCharsetConverters=true`来在`gcj`库之外强制转换字符，或者使用另一个JDK。

######23.3.15.10: Updating a table that contains a `primary key` that is either `FLOAT` or compound primary key that uses `FLOAT` fails to update the table and raises an exception.

Connector/J添加会添加一个条件到`WHERE`子句以便在`UPDATE`过程中来检查旧的主键值。如果没有匹配的，Connector/J会认为这是一个失败条件，然后抛出一个异常。

这个问题是由于在所提供的值和数据库中存在的值的有舍入的差异，所以不会匹配，自然就会更新失败。这个问题会影响所有的查询，不单单是Connector/J的查询。

避免使用`FLOAT`类型的主键来解决这个问题。如果主键必须使用浮点类型的列，那么使用`DOUBLE`或者`DECIMAL`类型替换`FLOAT`。

######23.3.15.11: You get an `ER_NET_PACKET_TOO_LARGE` exception, even though the binary blob size you want to insert using JDBC is safely below the `max_allowed_packet` size。

这是因为`com.mysql.jdbc.PreparedStatement.streamToBytes()`中的`hexEscapeBlock()`方法将你的数据加倍了。

######23.3.15.12: What should you do if you receive error messages similar to the following: “Communications link failure – Last packet sent to the server was X ms ago”?

一般来说，这个错误暗示网络连接已经被关闭了。可能有几个原因：

* 防火墙或路由器可能限制闲置连接（MySQL客户端/服务器协议不会ping）。
* MySQL服务器会关闭超过了`wait_timeout`或者`interactive_timeout`阈值的闲置连接。

为了解决这些问题，可以使用下面的几点方法。如果使用的是5.1.13或更高版本的Connector/J，你将会看到相比于旧版本，新版本改善了信息层次。旧版本很简单的显示了最后的一个数据包到达服务器的时间，这个时间经常是0ms以前。这些信息作用有限，可能刚刚发送了一个数据包，但是服务器的有几个小时没有接受到数据包了。Connector/J从服务器接收到的最后一个数据包的时间间隔将会是很有用的，所以这个信息如果没有出现在异常信息中，建议将Connector/J升级到最新版本。

此外，如果最后一个数据包发送/接收时间超过了`wait_timeout`或者`interactive_timeout`阈值，也将会记录在异常信息中。

虽然网络连接是易变的，但是下面的措施将会有效避免这些问题：

* 当使用连接池中的连接时，确保连接是有效的。使用以`/**/`开始的查询来执行轻量级的ping而不是完整的查询，注意，ping的语法必须符合指定的规则。
* 当其他应用逻辑在执行时，使连接对象的闲置时间最小化。
* 在使用连接前验证连接是否有效，如果连接已经闲置一段时间了。
* 确保`wait_timeout`和`interactive_timeout`设置得足够大。
* 确保`tcpKeepalive`启用。
* 确保任何可配置的防火墙或者路由器设定的超时时间大于连接预期的闲置时间。

>#####注意
>如果连接已经被闲置了一段时间，不要期望没有任何问题的重用连接。如果要重用闲置了一段时间的连接，确保在使用之前测试了连接的有效性。

######23.3.15.13: Why does Connector/J not reconnect to MySQL and re-issue the statement after a communication failure, instead of throwing an Exception, even though I use the `autoReconnect` connection string option?

这个问题有几个原因。第一个原因是事务的完整性。MySQL用户手册中声明：没有安全的方法重连到MySQL服务器，现有的方法会有连接垮掉或者数据库信息丢失的风险。考虑下面一系列的示例语句：

```java

conn.createStatement().execute(
"UPDATE checking_account SET balance = balance - 1000.00 WHERE customer='Smith'");
conn.createStatement().execute(
"UPDATE savings_account SET balance = balance + 1000.00 WHERE customer='Smith'");
conn.commit();

```

在对`checking_account`执行`UPDATE`语句之后，与服务器的连接失败，如果没有异常抛出，并且应用程序没有感知到这个问题，那么它将继续执行。然而，在这种情况下服务器并没有提交第一个事务，所以事务将回滚。但是下一个事务继续执行，并且将`savings_account`余额更增加了1000。这个应用程序没有接收到异常，所以最终提交了第二个事务，因为提交的第二个事务是在另一个新连接中执行的。这个例子是关于存款的，而不是网络传输。

注意到以`autocommit`方式执行没有解决这个问题。当Connector/J遇到了一个通讯问题时，不能确定服务器是否执行了成功。下面情况同样是可能的：
* 服务器没有接收到SQL，因此在服务器端没有相关的处理。
* 服务器接收到了SQL，并且执行成功了，但是客户端没有收到服务器的返回状态。

如果启用了`autocommit`,当发生了通讯异常时，不可能保证数据的状态。向服务器发送的请求被正确接收，或者没有。在客户端接收到服务器确认信息（或数据）之前，你能知道的仅仅是此时与服务器通讯失败了。这不仅仅影响`autocommit`的语句。如果在执行`Connection.commit()`过程中发生了通讯问题，那么引起的问题就是事务是否在通讯失败之前提交到了MySQL服务，或者是服务是否成功接收了服务请求。

产生这个问题的第二个原因可能是事务上下文范围的数据可能是易丢失的，例如：

* 临时表
* 用户定义变量
* 服务端的预处理语句

当连接失败时，这几项丢失，并且进行了重连而没有产生异常，那么这将对应用程序的执行产生不利的影响。

总之，通讯异常会产生不安全的情形，对于Connector/J来说，在这种情形下会忽略掉通讯错误并且进行重连。应用程序注意到这中错误很有必要。对于应用程序开发者来说，要确定在发生连接错误时如何让程序继续进行下去。

######23.3.15.14: How can I use 3-byte UTF8 with Connector/J?

要使用3字节的UTF8编码，可以在连接字符串中设置`characterEncoding=utf8`和`useUnicode=true`。

######23.3.15.15: How can I use 4-byte UTF8, utf8mb4with Connector/J?

要使用4字节UTF8编码，可以在MySQL服务端配置`character_set_server=utf8mb4`。只要在连接字符串中没有设置`characterEncoding`，Connector/J将使用这个设置。这等同于自动检测字符集。

######23.3.15.16: Using `useServerPrepStmts=false` and certain character encodings can lead to corruption when inserting BLOBs. How can this be avoided?

当使用某种字符编码时，如SJIS，CP932，BIG5等，BLOB类型数据可能包含不能被解释的字符，例如反斜线，'\'。当向数据库中插入BLOB类型的数据时，这将导致数据丢失。如果要避免这种情况，需要这样做：

1. 设置连接字符串选项`useServerPrepStmts`为`true`。
2. 设置`SQL_MODE`为`NO_BACKSLASH_ESCAPES`。





[13-7-1-4]:../Chapter_13/13.07.01_Account_Management_Statements.md
[22-3-3]:22.03.03_ConnectorJ_Installation.md
[22-3-5-1]:22.03.05_ConnectorJ_JDBC_Reference.md
[c-5-2-3]:../Appendix_C/C.05.02_Common_Errors_When_Using_MySQL_Programs.md